# Splunk Universal Forwarder - inputs.conf
# Location: C:\Program Files\SplunkUniversalForwarder\etc\apps\Splunk_TA_windows\local\inputs.conf
# Applied on: Windows 11 (Target-PC) and Windows Server 2022 (AD-SERVER01)
# Forwards logs to Splunk server at 192.168.10.10:9997
# All logs indexed under: endpoint

[WinEventLog://Application]
index = endpoint
disabled = false

[WinEventLog://Security]
index = endpoint
disabled = false

[WinEventLog://System]
index = endpoint
disabled = false

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = endpoint
disabled = false
renderXml = true
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
